name: giphy_search
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  provider: ^4.0.5
  dio: 3.0.9
  shimmer: ^1.1.2
  cached_network_image: ^2.2.0+1
  fluttertoast: 7.0.4


  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true

